# Site settings
title: ownCluster
author: "Jörn Friedrich Dreyer"
#tagline: Notes on scaling web applications on a banana pi cluster.
email: jfd+owncluster@butonic.de
description: > # this means to ignore newlines until "baseurl:"
  Notes on scaling web applications on a banana pi cluster.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://owncluster.de" # the base hostname & protocol for your site
paginate: 1

twitter_username: butonic
github_username:  owncluster

highlighter: pygments

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/owncluster/"
  - twitter: "https://twitter.com/butonic/"

# Build settings

markdown: redcarpet
#kramdown:
#  input: GFM

# Serve settings
host: localhost

# Outputting
permalink: /:year/:month/:day/:title

excerpt_separator: "<!-- more -->"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]

picture:
  source: "assets/images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        class: "default-pict"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"
